### 배열의 연산

In [34]:
import numpy as np


a = np.random.randint(1,10, (2,3))  #1-10까지 random 값으로 2행 3열로 배열 생성
b = np.random.randint(1,10, (2,3))

print(a)
print(b)

print('-'*50)


print(a+b)  #각 행,열의 일치하는 값끼리 서로 연산이 된다
print(a-b)
print(a*b)
print(a/b)
print('-'*50)
print(a**2)
print(b**2)
print(a*5)
print(a>b)

[[7 7 5]
 [2 6 3]]
[[1 3 9]
 [9 1 2]]
--------------------------------------------------
[[ 8 10 14]
 [11  7  5]]
[[ 6  4 -4]
 [-7  5  1]]
[[ 7 21 45]
 [18  6  6]]
[[7.         2.33333333 0.55555556]
 [0.22222222 6.         1.5       ]]
--------------------------------------------------
[[49 49 25]
 [ 4 36  9]]
[[ 1  9 81]
 [81  1  4]]
[[35 35 25]
 [10 30 15]]
[[ True  True False]
 [False  True  True]]


In [12]:
import numpy as np

a = np.random.randint(1,5,(3,4))
b = np.random.randint(1,5,(3,4))

print(a)
print(b)


[[1 1 2 4]
 [2 4 3 4]
 [1 4 1 2]]
[[1 1 4 2]
 [4 2 1 3]
 [1 4 1 2]]


In [42]:
import numpy as np


arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

newarr = np.array_split(arr, 2)

print(newarr)

TypeError: Field elements must be 2- or 3-tuples, got '6'

In [20]:
import numpy as np

arr = np.array(['banana' , 'cherry' , 'strawberry' , 'grape', '귤'])

print(np.sort(arr))  #오름차순으로 정렬




['banana' 'cherry' 'grape' 'strawberry' '귤']


In [43]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6],[7,8,9],[9,10,11]])

print(arr.mean())   #배열을 하나의 값으로 연산하는 함수들
print(arr.sum())
print(arr.std())
print(arr.var())
print(arr.min())
print(arr.max())






6.25
75
3.139134700306227
9.854166666666666
1
11


In [27]:
import numpy as np

arr = np.arange(10)   #arange = array range의 약자임

print(np.sqrt(arr))
print(np.exp(arr))

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]


In [32]:
import numpy as np


a = np.random.randint(0,10, (2,3))

print(a)


np.savetxt('./data/score.csv' , a)



[[0 6 1]
 [9 9 3]]


In [33]:
b = np.loadtxt('./data/score.csv' , np.int32)
print(b)

[[0 6 1]
 [9 9 3]]
